### ISSUE TITLE
Interchanged Item Frame Textures for End Stone Brick Walls and Nether Brick Walls

### ISSUE THREAD

**Issue by TraxTRL** [PowerNukkitX/PowerNukkitX#952]
# 🐞 Bug report

### 📸 Screenshots / Videos
![353b4ef9-c803-412f-bd45-b7939a705df7~2](https://user-images.githubusercontent.com/56545793/213912603-c99da860-1f31-463a-b50d-6e801e715b3c.png)

### ▶ Steps to Reproduce
1. Place down item frames
2. Put the two items in the item frames
3. See bug

### ✔ Expected Behavior
The Nether Brick Wall will have the Nether Brick Wall texture and the End Stone Brick Wall will have the End Stone Brick Wall texture in the item frame.

### ❌ Actual Behavior
The Nether Brick Wall will have the End Stone Brick Wall texture and the End Stone Brick Wall will have the Nether Brick Wall texture in the item frame

**Comment by smartcmd** [comment]
It is a client bug
![image](https://user-images.githubusercontent.com/60499296/216064727-84f3d478-a4a0-4187-92e9-faf8baeca29f.png)
![image](https://user-images.githubusercontent.com/60499296/216064742-d286068a-8ecb-447b-a4ad-5997c59ab047.png)
BDS had changed to use block state instead of using id + damage

**Comment by CoolLoong** [comment]
1.19.70 does not occur
